version: 0.0
os: linux
files:
  - source: webapp
    destination: /var/webapps
  - source: webapp/assignment2/target/assignment2-0.0.1-SNAPSHOT.war
    destination: /opt/tomcat/webapps/app.war
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 180
      runas: centos
  AfterInstall:
    - location: scripts/setup_spring.sh
      timeout: 180
      runas: centos
    - location: scripts/setup_cwagent.sh
      timeout: 180
      runas: centos